# Generated by Django 3.1.3 on 2020-11-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201126_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referred_by',
        ),
    ]
