# Generated by Django 3.1.3 on 2020-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201126_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('account', 'Bronze'), ('account', 'Silver'), ('account', 'Gold'), ('account', 'Platinum')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
