# Generated by Django 3.1.3 on 2020-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201128_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_withdrawal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_next_payout',
            field=models.DateField(null=True),
        ),
    ]
