# Generated by Django 3.1.3 on 2020-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201128_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_next_payout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
