# Generated by Django 3.1.3 on 2020-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201128_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bitcoin_wallet',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
