# Generated by Django 3.1.3 on 2020-12-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201201_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='earning_balance',
            field=models.FloatField(default=0),
        ),
    ]
