# Generated by Django 3.1.3 on 2020-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201201_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prove_of_payment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
