# Generated by Django 3.1.3 on 2020-12-01 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_invoice_prove_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
