# Generated by Django 3.1.3 on 2020-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payout_method',
            field=models.CharField(default='naira-account', max_length=50),
        ),
    ]
