# Generated by Django 3.1.3 on 2020-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_withdrawal_payout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(default='processing', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
